### PR TITLE
Non developer readme contribution

### PR DESCRIPTION
**Pull request by NathanJPlummer**
Added rewritten non-technical section based on your comments.  I did believe there was a need to address what a DSL specification was for non-technical readers to properly understand the project but this has been shortened to a few short paragraphs.

### CODE REVIEW

**Comment by mcstepp** [comment]
Looks good to me!

**Comment by NathanJPlummer** [comment]
Great!  Unless I hear differently from you in the next hour, I'll do the official pull request on the source project and we can mark this assignment as complete.  I'll let you know when it's done.  Great working with you!

**Comment by mcstepp** [comment]
Make sure to rebase all the commits into one commit before submitting a pull request!

**Comment by NathanJPlummer** [comment]
Thanks for the reminder!  Will do.  (I'll go over the contributing file again).

**Pull request merged**
